# Generated by Django 4.0.1 on 2022-01-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_name',
        ),
    ]
